apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.rootPassword | quote }}
