apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels: {{- include "minio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      name: s3
  selector:
    app: {{ include "minio.fullname" . }}
