apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minio.fullname" . }}
  labels: {{- include "minio.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "minio.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: { app: {{ include "minio.fullname" . }} }
  template:
    metadata:
      labels:
        app: {{ include "minio.fullname" . }}
        {{- include "minio.labels" . | nindent 8 }}
    spec:
      containers:
      - name: minio
        image: {{ .Values.image }}
        args: ["server", "/data"]
        envFrom:
        - secretRef:
            name: {{ include "minio.fullname" . }}-secret
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.storageSize }}
