apiVersion: v1
kind: Service
metadata:
  name: {{ include "sampleapp.fullname" . }}
  labels:
    {{- include "sampleapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8081
    name: http
  selector:
    app: {{ include "sampleapp.fullname" . }}
