image:
  repository: ghcr.io/your-username/krescue-sample    # TODO: change to your GH user later
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  port: 8081

ingress:
  enabled: true
  className: nginx
  host: sample.local
