configuration:
  backupStorageLocation:
  - name: default
    provider: aws
    bucket: {{BUCKET}}
    config:
      s3Url: {{S3_URL}}            # e.g., http://minio.krescue-primary.svc.cluster.local:9000
      s3ForcePathStyle: true
      region: us-east-1
  volumeSnapshotLocation: []
credentials:
  useSecret: true
  existingSecret: velero-credentials
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.9.0
    volumeMounts:
      - mountPath: /target
        name: plugins
